### ISSUE TITLE
ipv6 problem?

### ISSUE THREAD

**Issue by EricDkk** [jaysoffian/eap_proxy#1]
First, thank you and your project, it works like a charm.
My question is whether your ERL get ipv6 WAN address on eth0 vlan?

**Comment by jaysoffian** [comment]
I haven't tried, so I don't know. Search the forums - some folks copied over the IPv6 settings from their RG, others apparently got dhcp6 to work. I think it depends if you're area is using 6rd or native IPv6.

**Comment by EricDkk** [comment]
Thank you!

**Comment by jaysoffian** [comment]
I was able to get IPv6 to work. It's currently using 6rd and statically configured so if my IPv4 changes it will break, but here's the relevant IPv6 configuration I'm using:

```
set interfaces ethernet eth1 address 'DELEGATEDPREFIX::1/64'
set interfaces tunnel tun0 address 'DELEGATEDPREFIX::1/60'
set interfaces tunnel tun0 description 'AT&T 6rd tunnel'
set interfaces tunnel tun0 encapsulation sit
set interfaces tunnel tun0 local-ip XX.XX.XX.XX
set interfaces tunnel tun0 multicast disable
set interfaces tunnel tun0 remote-ip 12.83.49.81
set interfaces tunnel tun0 ttl 255
set protocols static interface-route6 '::/0' next-hop-interface tun0
set service dns forwarding options enable-ra
set service dns forwarding options 'dhcp-range=::1,constructor:eth1,ra-names,86400'
```

The `DELEGATEDPREFIX` is the "6rd Delegated Prefix" copied from my Pace 5268 (see "6rd IPv6 Internet Connection" in the router's web UI under Settings > Broadband). I was given a /60 prefix, but yours may be different. I saw no reason to use anything larger than /64 for my LAN interface (eth1).

Note that I'm using `dnsmasq` for IPv6 router advertisements. You could use `radvd`, but I didn't see any reason to run yet another process since I'm already using `dnsmasq` for DHCP (`set service dhcp-server use-dnsmasq enable`).

If you aren't already using `dnsmasq` for DHCP, you might want to use `radvd` instead. [See the example here](https://help.ubnt.com/hc/en-us/articles/204960044-EdgeRouter-Enable-IPv6-support-via-CLI) (it's the `router-advert` section).


Don't forget to enable `ip6tables`:

```
set firewall ipv6-name WAN6_IN default-action drop
set firewall ipv6-name WAN6_IN description 'WAN to internal'
set firewall ipv6-name WAN6_IN rule 10 action accept
set firewall ipv6-name WAN6_IN rule 10 description 'Allow established/related'
set firewall ipv6-name WAN6_IN rule 10 state established enable
set firewall ipv6-name WAN6_IN rule 10 state related enable
set firewall ipv6-name WAN6_IN rule 20 action drop
set firewall ipv6-name WAN6_IN rule 20 description 'Drop invalid state'
set firewall ipv6-name WAN6_IN rule 20 state invalid enable
set firewall ipv6-name WAN6_IN rule 30 action accept
set firewall ipv6-name WAN6_IN rule 30 description 'Allow ICMPv6''
set firewall ipv6-name WAN6_IN rule 30 protocol icmpv6
set firewall ipv6-name WAN6_LOCAL default-action drop
set firewall ipv6-name WAN6_LOCAL description 'WAN to router'
set firewall ipv6-name WAN6_LOCAL rule 10 action accept
set firewall ipv6-name WAN6_LOCAL rule 10 description 'Allow established/related'
set firewall ipv6-name WAN6_LOCAL rule 10 state established enable
set firewall ipv6-name WAN6_LOCAL rule 10 state related enable
set firewall ipv6-name WAN6_LOCAL rule 20 action drop
set firewall ipv6-name WAN6_LOCAL rule 20 description 'Drop invalid state'
set firewall ipv6-name WAN6_LOCAL rule 20 state invalid enable
set firewall ipv6-name WAN6_LOCAL rule 30 action accept
set firewall ipv6-name WAN6_LOCAL rule 30 description 'Allow ICMPv6'
set firewall ipv6-name WAN6_LOCAL rule 30 protocol icmpv6
set interfaces ethernet eth0 vif 0 firewall in ipv6-name WAN6_IN
set interfaces ethernet eth0 vif 0 firewall local ipv6-name WAN6_LOCAL
```

Good luck. (I know there's 6rd-specific configuration commands, but I didn't use them and this seems to be working. All http://ipv6-test.com tests except for RDNS pass.

**Comment by EricDkk** [comment]
Thank you, my At&t gateway(5268AC) gets native dual-stack IPv6 after updating the firmware to latest firmware 10.5.6.529454. I setup IPV6-PD on ER-L but no luck, ER-L does not get IPV6 address.
There is a new problem after I rebooted the whole system, the bypass was not working anymore. I set eap_proxy running as --debug mode and found the ER-L getting failure EAP packets from ONT. I will post details ASAP. Thank you.

**Comment by jaysoffian** [comment]
I'm not sure about the EAP failures. I'd try plugging the 5268AC back in directly. Maybe it was due to the firmware upgrade.

**Comment by jaysoffian** [comment]
@EricDkk see the discussion in https://github.com/jaysoffian/eap_proxy/issues/3 for why you may have had trouble with IPV6-PD. Seems to be a bug in EdgeOS where it wont' start `dhcp6c` on a VLAN interface.

**Comment by EricDkk** [comment]
@jaysoffian Thanks for sharing that.
Here are the log records I got. Is this happening because of the incorrect MAC address?
```
ubnt eap_proxy[1516]: proxy_loop starting
ubnt eap_proxy[1516]: eth2: e0:22:04:06:XX:xx > 01:80:c2:xx:xx:xx, EAPOL start (1) v2, len 0 > eth0
ubnt eap_proxy[1516]: eth0: 00:90:d0:63:xx:xx > e0:22:04:06:xx:xx, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
ubnt eap_proxy[1516]: eth0: 00:90:d0:63:xx:xx > e0:22:04:06:xx:xx, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
ubnt eap_proxy[1516]: eth0: 00:90:d0:63:xx:xx > e0:22:04:06:xx:xx, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
ubnt eap_proxy[1516]: eth0: 00:90:d0:63:xx:xx > 01:80:c2:xx:xx:xx, EAP packet (0) v1, len 4, Failure (4) id 2, len 4 [0] > eth2
```

**Comment by jaysoffian** [comment]
Setting the MAC address wrong shouldn't affect the 802.1x process since the MAC addresses are actually proxied. It would prevent DHCP from working, but this is failing before that point.

Are any packets exchanged after this point? I just looked at the logs on mine and I get an early failure as well, followed by an EAPOL start from the RG, then the exchange succeeds. Here's a successful exchange after a reboot of my ERL:

```
Sep 13 07:06:28 router eap_proxy[2215]: proxy_loop starting
Sep 13 20:50:29 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 1, len 15 [11] > eth2
Sep 13 20:50:59 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 1, len 15 [11] > eth2
Sep 13 20:51:29 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 4, Failure (4) id 1, len 4 [0] > eth2
Sep 13 20:51:29 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
Sep 13 20:51:40 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAPOL start (1) v2, len 0 > eth0
Sep 13 20:51:40 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
Sep 13 20:51:43 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 22, Response (2) id 2, len 22 [18] > eth0
Sep 13 20:51:43 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 6, Request (1) id 3, len 6 [2] > eth2
Sep 13 20:51:45 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 220, Response (2) id 3, len 220 [216] > eth0
Sep 13 20:51:45 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 1020, Request (1) id 4, len 1020 [1016] > eth2
Sep 13 20:51:47 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 6, Response (2) id 4, len 6 [2] > eth0
Sep 13 20:51:47 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 1020, Request (1) id 5, len 1020 [1016] > eth2
Sep 13 20:51:50 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 6, Response (2) id 5, len 6 [2] > eth0
Sep 13 20:51:50 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 1020, Request (1) id 6, len 1020 [1016] > eth2
Sep 13 20:51:51 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 6, Response (2) id 6, len 6 [2] > eth0
Sep 13 20:51:51 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 710, Request (1) id 7, len 710 [706] > eth2
Sep 13 20:51:54 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 1408, Response (2) id 7, len 1408 [1404] > eth0
Sep 13 20:51:54 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 6, Request (1) id 8, len 6 [2] > eth2
Sep 13 20:51:56 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 1404, Response (2) id 8, len 1404 [1400] > eth0
Sep 13 20:51:56 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 6, Request (1) id 9, len 6 [2] > eth2
Sep 13 20:51:59 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 893, Response (2) id 9, len 893 [889] > eth0
Sep 13 20:51:59 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > e0:22:02:38:e5:00, EAP packet (0) v1, len 69, Request (1) id 10, len 69 [65] > eth2
Sep 13 20:52:01 router eap_proxy[2215]: eth2: e0:22:02:38:e5:00 > 01:80:c2:00:00:03, EAP packet (0) v2, len 6, Response (2) id 10, len 6 [2] > eth0
Sep 13 20:52:02 router eap_proxy[2215]: eth0.0: restarting dhclient
Sep 13 20:52:08 router eap_proxy[2215]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 4, Success (3) id 10, len 4 [0] > eth2
```

**Comment by EricDkk** [comment]
I can tell something wrong with the 802.1x process, it ends an dead loop.
```
eth2: e0:22:04:xx:xx:xx > 01:80:c2:00:00:03, EAPOL start (1) v2, len 0 > eth0
[2015-01-02 09:18:33,184]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 1, len 15 [11] > eth2
[2015-01-02 09:19:03,481]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 1, len 15 [11] > eth2
[2015-01-02 09:19:33,778]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 4, Failure (4) id 1, len 4 [0] > eth2
[2015-01-02 09:19:33,782]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
[2015-01-02 09:20:04,075]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
[2015-01-02 09:20:34,372]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
[2015-01-02 09:21:04,669]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 4, Failure (4) id 2, len 4 [0] > eth2
[2015-01-02 09:21:04,673]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 3, len 15 [11] > eth2
[2015-01-02 09:21:34,966]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 3, len 15 [11] > eth2
[2015-01-02 09:22:05,263]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 3, len 15 [11] > eth2
[2015-01-02 09:22:35,560]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 4, Failure (4) id 3, len 4 [0] > eth2
[2015-01-02 09:22:35,564]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 4, len 15 [11] > eth2
[2015-01-02 09:23:05,857]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 4, len 15 [11] > eth2
[2015-01-02 09:23:36,154]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 4, len 15 [11] > eth2
[2015-01-02 09:24:06,452]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 4, Failure (4) id 4, len 4 [0] > eth2
[2015-01-02 09:24:06,456]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 5, len 15 [11] > eth2
[2015-01-02 09:24:36,748]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 5, len 15 [11] > eth2
[2015-01-02 09:25:07,045]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 5, len 15 [11] > eth2
[2015-01-02 09:25:37,342]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 4, Failure (4) id 5, len 4 [0] > eth2
[2015-01-02 09:25:37,346]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 6, len 15 [11] > eth2
[2015-01-02 09:26:07,639]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 6, len 15 [11] > eth2
[2015-01-02 09:26:37,937]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 15, Request (1) id 6, len 15 [11] > eth2
[2015-01-02 09:27:08,233]: eth0: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP packet (0) v1, len 4, Failure (4) id 6, len 4 [0] > eth2
```

**Comment by jaysoffian** [comment]
Sorry, I'm not sure what's going on. I see only a single EAPOL request from your RG then everything after that is coming in on the ONT port, and I don't see anything from the RG. Maybe try running without the `--ignore-when-wan-up` option. Also, please make sure you have the latest version of `eap_proxy.py` from this repo.

I assume the RG still works correctly if it's directly connected to the ONT, right?

**Comment by EricDkk** [comment]
Yes, RG is running correctly if it connects to the ONT directly.
I will try run it without --ignore-when-wan-up option.

**Comment by EricDkk** [comment]
This is the error msg```err=15 name=EAPOL_FAILED redirect``` from RG log page.

**Comment by jaysoffian** [comment]
This was working before you upgraded the RG but hasn't worked since you upgraded, is that correct?

**Comment by EricDkk** [comment]
Yes. I downgraded the RG but no luck.

**Comment by jaysoffian** [comment]
Let's try this.

1. Kill the running `eap_proxy.py` and launch it directly as follows:
    `sudo /usr/bin/python /config/scripts/eap_proxy.py --debug-packets IF_WAN IF_ROUTER 2>&1 | tee eap_proxy.log`
2. Unplug the RG's power.
3. Unplug and re-plug the ONT's ethernet connection from the ERL.
4. Re-plug the RG's power.

The RG should power-up, then send an EAPOL start and then the negotiation will continue from there. Meanwhile, `eap_proxy.py` will output a bunch of debugging info. Hit ctrl-c once the negotiation has finished (succeeded or failed) and upload the contents of `eap_proxy.log` as a gist. XX out your RG's ethernet address if you want. I'll see what I can figure out.

**Comment by EricDkk** [comment]
Thanks, I'll upload the result ASAP.

**Comment by jaysoffian** [comment]
Can you also run this in a separate shell on the ERL and include its output too?

    sudo tcpdump -XX -vvv -e -i IF_ROUTER ether proto 0x888e

**Comment by EricDkk** [comment]
Eap_proxy.log:
[https://gist.github.com/EricDkk/caa025ec71a29b9992cb5940eb860d12](url)

tcpdump result:
[https://gist.github.com/EricDkk/5eae4fd59e5dd6b7c81f801262b31717](url)

**Comment by jaysoffian** [comment]
So, I don't know why it's failing. From what I can tell, the RG sends an EAPOL Start. The ONT replies requesting an identity (`Type Identity (1), Identity: User Name:`). The RG never replies to that. The ONT asks a few more times then sends a failure packet.

The question is why the RG isn't replying to the identity request from the ONT. I do not know the answer. I don't really know the details of how EAPOL works. I'll have to read the specs to better understand what may be going wrong.

The proxy just copies the bits from eth0 to eth2, (and vice-versa) and that appears to be working correctly.

I'm pretty busy right now, so I can't promise when I'll be able to look into this further. The proxy still works fine for me. What's really confusing here is that the initially worked for you. I don't know what changed to break it.

:-(

**Comment by jaysoffian** [comment]
Well now here's one difference. From a tcpdump off my ERL:

`01:29:39.415647 e0:22:02:38:XX:XX (oui Unknown) > 01:80:c2:00:00:03 (oui Unknown), ethertype 802.1Q (0x8100), length 60: vlan 0, p 3, ethertype EAPOL, EAPOL start (1) v2, len 0`

Notice the 802.1Q vlan 0 indication. That's missing from your tcpdump output. Well now that's somewhat odd. I don't have any VLANs configured on my RG (eth2) interface. And the proxy frankly doesn't do anything with 802.1Q... that's handled transparently by the kernel.

What are you using for your `IF_WAN` and `IF_ROUTER` arguments? Do you have a vif 0 configured on your `IF_WAN` interface? What version of EdgeOS are you running?

**Comment by EricDkk** [comment]
IF_WAN: eth0 and vlan on eth0 vif 0
IF_ROUTER: eth2
EdgeOS:1.9.7 hotfix3
Yes, I'm using ERL 3 port

**Comment by jaysoffian** [comment]
I'm still running `v1.9.1.1`. Maybe related to that? I'm really not sure.

**Comment by EricDkk** [comment]
The last firmware I used is 1.9.7 hotfix2, it works very well.
I will try new RG and update later.

**Comment by EricDkk** [comment]
I just tried new RG. the same result, 3 repeat requests 1 failure. And also I downgraded ER-L to 1.9.1.1

**Comment by EricDkk** [comment]
I replaced the ERL with a new one, it worked finally.

**Comment by jaysoffian** [comment]
I can't imagine why that made a difference, but I'm glad to hear it's working for you now.
