### ISSUE TITLE
Clarifications on EdgeRouter setup

### ISSUE THREAD

**Issue by claym** [jaysoffian/eap_proxy#11]
Wanted confirmation on the setup for the EdgeRouter - just edit the eap sh script with proper devices / mac addresses go?

I noticed you had additional sample configuration, and was hoping for clarification on what if anything needed to be done with that. 

Thank you!

**Comment by jaysoffian** [comment]
The sample is there for guidance. I don't recommend making using `eap_proxy` unless you understand the configuration. Good luck.
