### ISSUE TITLE
ERPoE-5 switched ports (eth2-eth4) do not forward unicast EAP packets from router

### ISSUE THREAD

**Issue by globalreset** [jaysoffian/eap_proxy#13]
I setup the ONT on eth0, my LAN on eth1, and the AT&T router (BGW210) on eth2 of my ERPoE-5 and ran the script interactively. I could see logoff and start requests from the router, to the multicast mac, that were forwarded on to the ONT. I could see Request and Failure packets from the ONT, both unicast and multicast, that were forwarded on to the AT&T router. But I couldn't see any Response packets from the AT&T router towards the ONT.

Eventually it dawned on me that some of the ports (eth2-4) are 'special' on the ERPoE-5 in that they share a switch interface. I didn't realize it until I tried to set a mac address on eth2 (thinking that maybe using the ONT mac on that port would help), which failed and reminded me that I couldn't because it was behind this hardware switch.

Swapping my LAN and AT&T router ports around solved my problem, but I seem to recall there being a performance issue with using the switch ports. Maybe it was that you can't get the full packet rate if you bridge eth2-4 with eth1, need to do some research again.

Anyways, I bring up the issue in case you were already aware and there was an easy solution to keep my AT&T router on the switched ports. Or, if you weren't aware, here's a reminder for the next poor soul spending hours banging his head on the keyboard trying to figure it out.

**Comment by jaysoffian** [comment]
Okay thanks for the info.

**Comment by jdewb** [comment]
wish to god I found this eight hours ago.
