### ISSUE TITLE
No external IP address

### ISSUE THREAD

**Issue by chinochao** [jaysoffian/eap_proxy#15]
I followed the setup and everything seemed to work, however I was not able to get an IP from ATT. In /var/log/messages I saw the requestes going to eth0 and eth2 but I never got the IP from ATT.

Is anyone else experincing the same issue?

**Comment by gsxryan** [comment]
ER-X-SFP here.  I cannot get this to work either.  I need some help filling in the gaps of these instructions.  IE:  WAN_IN, WAN_LOCAL is not initialized by default.  Interfaces should be commited before service rules.  

I'm using the following from another thread to INIT WAN_IN and WAN_LOCAL, but i feel so lost, just digging through the mud..

set firewall name WAN_IN default-action drop
set firewall name WAN_IN description 'WAN to internal'
set firewall name WAN_IN rule 10 action accept
set firewall name WAN_IN rule 10 description 'Allow established/related'
set firewall name WAN_IN rule 10 state established enable
set firewall name WAN_IN rule 10 state related enable
set firewall name WAN_IN rule 20 action drop
set firewall name WAN_IN rule 20 description 'Drop invalid state'
set firewall name WAN_IN rule 20 state invalid enable

set firewall name WAN_LOCAL default-action drop
set firewall name WAN_LOCAL description 'WAN to router'
set firewall name WAN_LOCAL rule 10 action accept
set firewall name WAN_LOCAL rule 10 description 'Allow established/related'
set firewall name WAN_LOCAL rule 10 state established enable
set firewall name WAN_LOCAL rule 10 state related enable
set firewall name WAN_LOCAL rule 50 action drop
set firewall name WAN_LOCAL rule 50 description 'Drop invalid state'
set firewall name WAN_LOCAL rule 50 state invalid enable

**Comment by cerealcable** [comment]
@chinochao probably need more logs / information since there's not much to go on other than "its not working".

@gsxryan The example configuration was, well...an example. The repo didn't give a full accounting of how to configure your firewall. You probably want to research on how to configure EdgeOS devices then once you've got it working without eap-proxy, it'll probably make a lot more sense.

**Comment by jaysoffian** [comment]
@cerealcable thanks for trying to help. I'm closing this issue since it's not specific enough.
