### ISSUE TITLE
eth0.0 problem

### ISSUE THREAD

**Issue by prvcy** [jaysoffian/eap_proxy#16]
Any idea why this is happening? ERLite with AT&T Fiber

ubnt@ubnt# commit
[ service nat rule 5010 outbound-interface eth0.0 ]
NAT configuration warning: interface eth0.0 does not exist on this system

[ interfaces ethernet eth0 firewall in name WAN_IN ]
Firewall config error: Rule set WAN_IN is not configured

[ interfaces ethernet eth1 ]
Address 192.168.1.1/24 is present on multiple interfaces

[ interfaces ethernet eth0 vif 0 firewall in name WAN_IN ]
Firewall config error: Rule set WAN_IN is not configured

Commit failed

**Comment by jaysoffian** [comment]
No, I'm sorry. It looks like you may have attempted to copy/paste the sample configuration. You'll have to adapt it as appropriate for your router.

**Comment by lzmaths** [comment]
I encounter the same failed error:
> Address 192.168.1.1/24 is present on multiple interfaces

I configure while connecting to edgerouter via eth0 whose ip address is 192.168.1.1, so I cannot set the ip of eth1 to be the same (192.168.1.1) while connecting to the router.

Anything that I missed? Thank you.

**Comment by prvcy** [comment]
@lzmaths I ended up using this guide exactly and got it working: https://github.com/Genghis1227/guide_eap_proxy
