### ISSUE TITLE
Usability as a layer-2 bridge?

### ISSUE THREAD

**Issue by chrissnell** [jaysoffian/eap_proxy#2]
I'm really interested in using this technique for my PFSense router but PF_RING doesn't exist in BSD land.  
I'm curious if this proxy would still work if the WAN port was layer 2 bridged to a "router" port that was connected to my PFSense router.  I don't have the little Ubiquiti router and I was wondering if you could test it for me before I go buy one.  

```
                   +--------------------+           +------------------+
------/ONT/--------+                    +-----------|  PFSense Layer 3 |
                   |     EdgeRouter     |           |      Router      | 
                   | Transparent Bridge |           +---------+--------+
                   |                    |                     |
                   +---------+----------+                   /LAN/
                             | 
                             |
                       +-----+-----+
                       |AT&T Router|
                       +-----------+

```

I looked into writing this for netmap (BSD's alternative to PF_RING) but the API is just gnarly and I write in Go, not C.

**Comment by jaysoffian** [comment]
I'm not able to test this configuration. In any case, the ERL doesn't have h/w accelerated bridging so the performance would be awful.

**Comment by chrissnell** [comment]
Good to know.  Thanks @jaysoffian

**Comment by shaddow825** [comment]
The ER-X or ER-Poe-5 have a built-in switch that might be useful in this scenario

**Comment by thford89** [comment]
I was able to do this with a ERPOE-5 without issue and tested on a edge router x. 

eth2-eth4 are switching ports and will connect the ONT and PFSense box to two of the ports. Clone the MAC address on the pfsense box to match the MAC on the AT&T router. 

Install the script to run switch0 or the port the ONT is connected to and eth1 - assuming you kept eth1 for the AT&T router. 

I would suggest setting a management port of eth0 and connecting it to LAN. Block all management from other ports on the ER. 

If you have a block of static IPs the process is a little more complicated but several options are available.
