### ISSUE TITLE
Losing WAN on USG reboot, requires RG reconnect

### ISSUE THREAD

**Issue by missedtheapex** [jaysoffian/eap_proxy#20]
**Problem:**
If the USG is rebooted, there is no WAN connectivity until I do one of two things: a) disconnect the cable between USG’s LAN2 and the RG’s ONT port, then reconnect it, or b) reboot the RG. 

**My setup:** 
AT&T Fiber ONT to USG 3 WAN  (USG firmware 4.4.41.5193700)
BGW210-700 Residential Gateway behind USG on LAN2  (RG firmware 1.10.9)

USG is running eap_proxy, setup successfully according to the instructions at https://medium.com/@mrtcve/at-t-gigabit-fiber-modem-bypass-using-unifi-usg-updated-c628f7f458cf

Here is my eap_proxy.sh content:

`IF_WAN=eth0`
`IF_ROUTER=eth2`
`CONFIG_OPTIONS=(`
`   --restart-dhcp --ignore-when-wan-up --ignore-logoff --ping-gateway --set-mac)`
`DAEMON_OPTIONS=(--daemon --pidfile /var/run/eap_proxy.pid --syslog)`
`/usr/bin/python /config/scripts/eap_proxy.py \`
`     "$IF_WAN" "$IF_ROUTER" "${CONFIG_OPTIONS[@]}" "${DAEMON_OPTIONS[@]}" &`

**Discussion:**
I don’t have to do anything inside the USG after a reboot; the eap_proxy script is already running and waiting to pass the authentication. In fact, it quickly regains authentication after the RG is disconnected and reconnected. But until I do something (physically dis-/re-connect or reboot) to make the RG request authentication, my network just sits there with no Internet, and the broadband light on the RG flashes red indefinitely. Even if I try re-running eap_proxy, it doesn’t fix the connection.

I also notice that after the USG reboot, my USG’s eth0.0 doesn’t get the RG’s MAC address assigned to it until after the RG reconnect/reboot event. The eap_proxy script includes the “--set-mac ” flag, and I don’t see any way to manually assign the MAC on a USG (like the manual method on an EdgeRouter). I was able to use an “ip set” command on eth0.0 to assign the MAC while the WAN is down, but it didn't doesn’t fix the issue. Reconnecting the RG is still necessary. 

Is this expected behavior? I see a lot of similar reboot issues when I search. Many seem to be related to eap_proxy.sh not launching on startup, but that’s definitely not my issue.

**Comment by jaysoffian** [comment]
My guess is that when the USG reboots, it drops link to the ONT and so the ONT de-authenticates it.

Unfortunately, there's nothing `eap_proxy` can do to force the RG to authenticate to the ONT, so until that occurs (such as when you reboot it), you won't have a connection.

I guess one thing you can try is down/up'ing the USG’s LAN2 port. Maybe that will do the equivalent of your (a) w/o you having to physically disconnect/reconnect. I'm sorry I can't tell you what command to issue as I'm not familiar with the USG CLI.
