### ISSUE TITLE
eap_proxy start error: unexpected poll event

### ISSUE THREAD

**Issue by drewmullen** [jaysoffian/eap_proxy#28]
thanks for taking the time to write up and support this project. im following [taylor's guide](https://blog.taylorsmith.xyz/att-uverse-modem-bypass-unifi-usg/) and am getting the following error

```
$ sudo python /config/scripts/eap_proxy.py --restart-dhcp --ignore-when-wan-up --ignore-logoff --ping-gateway --set-mac eth0 eth2
[2019-09-07 16:15:43,288]: starting proxy_loop
Traceback (most recent call last):
  File "/config/scripts/eap_proxy.py", line 864, in <module>
    sys.exit(main())
  File "/config/scripts/eap_proxy.py", line 860, in main
    return proxy(args, log)
  File "/config/scripts/eap_proxy.py", line 812, in proxy_loop
    proxy.proxy_loop()
  File "/config/scripts/eap_proxy.py", line 599, in proxy_loop
    self.on_poll_event(socks[fd], event)
  File "/config/scripts/eap_proxy.py", line 605, in on_poll_event
    raise IOError("[%s] unexpected poll event: %d" % (ifname, event))
IOError: [eth2] unexpected poll event: 8
```

any ideas on what might be causing?

edit* looks like i might not be the first person: https://medium.com/@todd.vu24/anyone-have-the-issue-after-trying-to-test-eap-proxy-py-5e7e0d6337

**Comment by jaysoffian** [comment]
What device are you trying to run this on?

What version of the OS?

**Comment by jaysoffian** [comment]
Looks like 8 is `EPOLLERR`, which is "Error condition happened on the associated file descriptor."

I'm not sure what would cause that. Maybe the interface going away or not being valid in the first place? It should retry after 10 seconds. Does the error keep repeating?

**Comment by jaysoffian** [comment]
I guess double-check that your USG is configured exactly as Taylor describes. The only thing I can think is something is wrong with eth2. Copy/paste the output of `show interfaces` here, but I'm pretty limited in the trouble shooting I can provide. The error doesn't provide me enough to go on, and there's really not any other diagnostic data available to the proxy.

**Comment by drewmullen** [comment]
thanks for your attention. i had to catch a flight out before i could try out your suggestions but ill get to it Friday. ill grab that commit to so we can see which of the 3 types it is at least (or "???" lol) . sorry about the delay, i really appreciate your quick responses! 

im using this code on a USG, ill get the version asap.

**Comment by drewmullen** [comment]
sorry this response took so long. i decided to kill AT&T and go with someone what doesnt force me to use their router

sorry we're not finding clarity on this issue but thanks for your attention and for providing this tool to the community
