### ISSUE TITLE
Strange issue with installation of eap_proxy for USG

### ISSUE THREAD

**Issue by osagher** [jaysoffian/eap_proxy#34]
I've followed religiously the instructions that Taylor Smith posted with eap_proxy to bypass the ATT router. When running the command 'sudo python /config/scripts/eap_proxy.py --restart-dhcp --ignore-when-wan-up --ignore-logoff --ping-gateway --set-mac eth0 eth2' I get the following output:

[2020-05-04 19:09:17,254]: starting proxy_loop
Traceback (most recent call last):
  File "/config/scripts/eap_proxy.py", line 869, in <module>
    sys.exit(main())
  File "/config/scripts/eap_proxy.py", line 865, in main
    return proxy(args, log)
  File "/config/scripts/eap_proxy.py", line 817, in proxy_loop
    proxy.proxy_loop()
  File "/config/scripts/eap_proxy.py", line 602, in proxy_loop
    self.on_poll_event(socks[fd], event)
  File "/config/scripts/eap_proxy.py", line 610, in on_poll_event
    "[%s] unexpected poll event: %s (%d)" % (ifname, ename, event)
IOError: [eth2] unexpected poll event: POLLERR (8)

show interfaces gives me the following - 
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address                        S/L  Description                 
---------    ----------                        ---  -----------                 
eth0         192.168.2.3/24                    u/u  WAN                         
eth1         192.168.1.1/24                    u/u  LAN                         
eth1.100     192.168.100.1/24                  u/u                              
eth2         -                                 A/D                              
lo           127.0.0.1/8                       u/u                              
             ::1/128                          

In search the forums, I see that this has been reported before, but I don't see a resolution.

Can you offer any insight into this?

Thanks for any help you can offer,

Oren

**Comment by pgullette** [comment]
This means your WAN2/LAN2 port on the USG is disabled. This is the default behavior, so not surprising. You need to enable the port which isn't in settings of the controller, but instead you can enable it from the devices page.

Click on your USG device, and go to the ports icon.

![image](https://user-images.githubusercontent.com/1252645/81586604-571cff00-937b-11ea-9bbb-e86060fe5667.png)

Click configure interfaces link where you will see that port is currently disabled. You can then enable that port to look like below:

![image](https://user-images.githubusercontent.com/1252645/81586660-761b9100-937b-11ea-9f52-689cc209cedb.png)

I am still working through my configuration dealing with a potential dhclient issue, but at least this should get you closer in your case.

**Comment by jaysoffian** [comment]
> Can you offer any insight into this?

Sorry, I don't use a USG. Please try @pgullette's suggestion.
