### ISSUE TITLE
Dream Machine Pro compatibility

### ISSUE THREAD

**Issue by RichBrew** [jaysoffian/eap_proxy#37]
Are there any plans to update this for Dream Machine Pro?

**Comment by jaysoffian** [comment]
If someone submits a PR, I'll accept it.

**Comment by zcramos** [comment]
What all would enabling this entail? I'm considering upgrading to a UDM Pro and would be willing to do a bit of legwork, but I'd have no idea where to start.

**Comment by kphonik** [comment]
Here's a good example, I used this successfully before switching to wpa_supplicant-udmpro: https://github.com/pbrah/eap_proxy-udmpro
