### ISSUE TITLE
ping gateway periodically

### ISSUE THREAD

**Issue by shaddow825** [jaysoffian/eap_proxy#4]
Can you add an option to ping the gateway every so often in case something goes wonkey upstream that doesn't affect DHCP until the lease expiration? It would minimize downtime due to not having to wait until the lease expiration to listen to the residential gateway to trigger a start. I assume you are always listening on the wan side for packets from att in case of any kind of periodic reauthentication requests?

**Comment by jaysoffian** [comment]
There's already a `--ping-gateway` option. The RG sends an EAPOL-Start packet once a second at least mine does). With `--ping-gateway`, the proxy will ping the gateway in response to the EAPOL-Start and only proxy the packet if the ping fails.

**Comment by jaysoffian** [comment]
Besides that pinging the gateway alone wouldn't help if your RG isn't sending EAPOL-Start packets. The proxy would also have to generate its own EAPOL-Start packet. Then what does it do with the replies from the ONT? The obvious answer is to pass them to the RG. But if the RG didn't initiate the logon with an EAPOL-Start, it's probably not going to respond to the packets from the ONT.

In any case, this sounds like a hypothetical scenario so I wouldn't be able to test what you're asking for.

**Comment by shaddow825** [comment]
When I stated "gateway" I meant the default gateway at At&t. You are right that option does what I want, I was looking for it to happen say every minute or so instead of just at startup. Looking to avoid a situation where like a week after establishing the connection att has something reboot/reset on their end and you aren't authenticated any longer. Now, since you are ignoring the EAPOL-Start from the RG and rather than passing them on to reauthenticate, and the lease hasn't expired, it's just sitting idle until the DHCP expires. If the periodic ping fails you can start paying attention to the RG EAPOL-Start messages again and authenticate as soon as ATT fixes any issue on their end. One thing I've learned over the years (with metro-E type ethernet connections, and not GPON however) is things happen upstream and interfaces don't see any changes. Now to be fair I don't know how the RG would handle such a situation (prob require a reboot) but we have the advantage of having an RG that is almost always sending EAPOL-Starts so we could recover without a reboot.

**Comment by jaysoffian** [comment]
To be clear: the `--ping-gateway` option does not apply ONLY at start. Whenever the RG sends an EAPOL-Start, the proxy will send an ICMP ECHO and if it doesn't get a reply within one second, then it forwards the EAPOL-Start. That should be enough to start a conversation between the ONT/RG which will conclude with an EAPOL Success from the ONT. When the proxy sees the Success packet, it will re-start dhcp.

**Comment by shaddow825** [comment]
Ohh ok, I misunderstood when on dslreports you said "I have my proxy configured to ignore the 5268 once my router has an IP" I figured once it was ignoring the RG the ping-gateway would end.

**Comment by jaysoffian** [comment]
I've updated the proxy since that post. That is how it behaved originally but the current versions behaves as I described above.
