### ISSUE TITLE
eth2 dropping every day around same time

### ISSUE THREAD

**Issue by FurmanSK** [jaysoffian/eap_proxy#47]
Hey @jaysoffian, first off, thanks for this tool. Really like it. Also, I'm not sure if this is an issue with your script or just with AT&T's router, but I am having it drop connection every day around the same times. I notice it because I lose connection to everything, even calls with work. Was wondering if you or anyone else has had anything like this on their side or if its something wrong with the actual router. 

I leave it turned on all the time once the EAP_Proxy was setup because when I would power it off, after a week or so my internet would stop working. I don't have the debug turned on with it but here is a log of when the event is happening.

```
Jun 10 15:43:11 USG zebra[623]: interface eth2 index 4 changed <UP,BROADCAST,MULTICAST>.
Jun 10 15:43:11 USG kernel: eth2: Link down
Jun 10 15:43:15 USG zebra[623]: interface eth2 index 4 changed <UP,BROADCAST,RUNNING,MULTICAST>.
Jun 10 15:43:15 USG kernel: eth2: 1000 Mbps Full duplex, port 2
Jun 10 15:43:39 USG zebra[623]: interface eth2 index 4 changed <UP,BROADCAST,MULTICAST>.
Jun 10 15:43:39 USG kernel: eth2: Link down
Jun 10 15:43:41 USG zebra[623]: interface eth2 index 4 changed <UP,BROADCAST,RUNNING,MULTICAST>.
Jun 10 15:43:41 USG kernel: eth2: 1000 Mbps Full duplex, port 2
Jun 10 15:43:51 USG zebra[623]: interface eth2 index 4 changed <UP,BROADCAST,MULTICAST>.
Jun 10 15:43:51 USG kernel: eth2: Link down
Jun 10 15:43:53 USG zebra[623]: interface eth2 index 4 changed <UP,BROADCAST,RUNNING,MULTICAST>.
Jun 10 15:43:53 USG kernel: eth2: 1000 Mbps Full duplex, port 2
Jun 10 15:45:24 USG eap_proxy[3018]: eth2: XX:XX:XX:XX:XX:XX > XX:XX:XX:XX:XX:XX, EAPOL start (1) v2, len 0 > eth0
Jun 10 15:45:24 USG eap_proxy[3018]: eth0.0: restarting dhclient

```

Notice, link goes down on eth2 where the AT&T router is. I'm a software engineer but networking was never my strong suit. Any help would be great but if its not related to your script then feel free to close. 

Thanks.

**Comment by jaysoffian** [comment]
I don't know why your connection is dropping, but the log snippet you included looks normal.

**Comment by FurmanSK** [comment]
Yeah I'm not sure why its dropping either. I'm going to try and just hook it back up as normal. If I do that, do I have to uninstall the eap_proxy off my USG? What's weird is it drops 3 time a day but the time frame moves to where now its around 9pm local vs. the log there shows 15:43 for that specific one. Not sure why the router link drops, but I assume it shuts off or reboots which I'm not sure why that kicks me off the internet. Could I have something configured wrong with eap_proxy? Anything I can look at to make sure its setup correctly and working as it should? I followed the guide few years ago so I'm not sure if anything has changed or anything I can look at or do.

**Comment by alsobrsp** [comment]
It is strange. I am having the same issue. It happens every day at the same time everyday that I restart my systems.

This is my log output.
`
Jul 23 10:38:06 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > ATT_ONT_MAC, EAP packet (0) v1, len 4, Failure (4) id 0, len 4 [0] > eth2
Jul 23 10:38:06 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > ATT_ONT_MAC, EAP packet (0) v1, len 15, Request (1) id 1, len 15 [11] > eth2
Jul 23 10:38:07 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 22, Response (2) id 1, len 22 [18] > eth0
Jul 23 10:38:36 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > ATT_ONT_MAC, EAP packet (0) v1, len 15, Request (1) id 1, len 15 [11] > eth2
Jul 23 10:38:36 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 22, Response (2) id 1, len 22 [18] > eth0
Jul 23 10:39:06 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > ATT_ONT_MAC, EAP packet (0) v1, len 15, Request (1) id 1, len 15 [11] > eth2
Jul 23 10:39:06 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 22, Response (2) id 1, len 22 [18] > eth0
Jul 23 10:39:06 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > ATT_ONT_MAC, EAP packet (0) v1, len 4, Failure (4) id 1, len 4 [0] > eth2
Jul 23 10:39:06 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > ATT_ONT_MAC, EAP packet (0) v1, len 15, Request (1) id 2, len 15 [11] > eth2
Jul 23 10:39:07 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 22, Response (2) id 2, len 22 [18] > eth0
Jul 23 10:39:07 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > USG_MAC, EAP packet (0) v1, len 6, Request (1) id 3, len 6 [2] > eth2
Jul 23 10:39:07 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 92, Response (2) id 3, len 92 [88] > eth0
Jul 23 10:39:07 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > USG_MAC, EAP packet (0) v1, len 1020, Request (1) id 4, len 1020 [1016] > eth2
Jul 23 10:39:08 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 6, Response (2) id 4, len 6 [2] > eth0
Jul 23 10:39:08 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > USG_MAC, EAP packet (0) v1, len 1020, Request (1) id 5, len 1020 [1016] > eth2
Jul 23 10:39:08 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 6, Response (2) id 5, len 6 [2] > eth0
Jul 23 10:39:08 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > USG_MAC, EAP packet (0) v1, len 479, Request (1) id 6, len 479 [475] > eth2
Jul 23 10:39:08 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 906, Response (2) id 6, len 906 [902] > eth0
Jul 23 10:39:08 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > USG_MAC, EAP packet (0) v1, len 6, Request (1) id 7, len 6 [2] > eth2
Jul 23 10:39:08 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 902, Response (2) id 7, len 902 [898] > eth0
Jul 23 10:39:08 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > USG_MAC, EAP packet (0) v1, len 6, Request (1) id 8, len 6 [2] > eth2
Jul 23 10:39:09 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 902, Response (2) id 8, len 902 [898] > eth0
Jul 23 10:39:09 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > USG_MAC, EAP packet (0) v1, len 6, Request (1) id 9, len 6 [2] > eth2
Jul 23 10:39:09 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 484, Response (2) id 9, len 484 [480] > eth0
Jul 23 10:39:09 usg01 eap_proxy[3374]: eth0: ATT_ROUTER_MAC > USG_MAC, EAP packet (0) v1, len 69, Request (1) id 10, len 69 [65] > eth2
Jul 23 10:39:09 usg01 eap_proxy[3374]: eth2: USG_MAC > ATT_ONT_MAC, EAP packet (0) v2, len 6, Response (2) id 10, len 6 [2] > eth0
Jul 23 10:39:09 usg01 eap_proxy[3374]: eth0.0: restarting dhclient

`

**Comment by FurmanSK** [comment]
@alsobrsp Are you seeing the actual interface show `Link down` like I do in my log? Mine is every day but not the same time. It is rolling the time. So today it happened at 11:35, tomorrow might happen 15 give or take minutes later, and it happens 3 times in that window.

I have just now put my router back behind the AT&T modem and enabled pass through. They are sending me a new modem I'll get in a couple days. I might try to go back to the script if I can. If not then I'll revert back.

**Comment by jaysoffian** [comment]
Again, I don't know why your connection is dropping. It is normal for the RG to reboot itself periodically. When that happens the ethernet port to which the RG is connected will do this:

```
Aug 19 17:29:28 router kernel: eth2: Link down
Aug 19 17:29:30 router kernel: eth2: 1000 Mbps Full duplex, port 3
Aug 19 17:29:50 router kernel: eth2: Link down
Aug 19 17:29:53 router kernel: eth2: 1000 Mbps Full duplex, port 3
Aug 19 17:29:59 router kernel: eth2: Link down
Aug 19 17:30:02 router kernel: eth2: 1000 Mbps Full duplex, port 3
```

In between reboots, the RG constantly sends EAPOL start packets, which `eap_proxy` ignores as long as it appears your Internet connection via the ONT is up:

```
Aug 19 20:41:11 router kernel: eth0: Link down
Aug 19 20:41:13 router kernel: eth0: 1000 Mbps Full duplex, port 1
Aug 19 20:41:21 router eap_proxy[2936]: eth2: e0:22:02:xx:xx:xx > 01:80:c2:xx:xx:xx, EAPOL start (1) v2, len 0
Aug 19 20:41:21 router eap_proxy[2936]: eth3.0: 75.60.xx2.5
Aug 19 20:41:21 router eap_proxy[2936]: ping: 75.60.xx0.1 success
Aug 19 20:41:21 router eap_proxy[2936]: eth2: ignoring e0:22:02:xx:xx:xx > 01:80:c2:xx:xx:xx, EAPOL start (1) v2, len 0
Aug 19 20:41:53 router eap_proxy[2936]: eth2: e0:22:02:xx:xx:xx > 01:80:c2:xx:xx:xx, EAPOL start (1) v2, len 0
Aug 19 20:41:53 router eap_proxy[2936]: eth3.0: 75.60.xx2.5
Aug 19 20:41:53 router eap_proxy[2936]: ping: 75.60.xx0.1 success
Aug 19 20:41:53 router eap_proxy[2936]: eth2: ignoring e0:22:02:xx:xx:xx > 01:80:c2:xx:xx:xx, EAPOL start (1) v2, len 0
...
```

I don't know why your Internet connection is dropping, but I don't think `eap_proxy` has anything to do with it. Normally the ONT only requires re-authentication if it loses link on its Ethernet connection, or apparently after a 1-2 week timeout.

**Comment by FurmanSK** [comment]
Okay, still odd that I'd lose it when those resets would happen at the exact same time. I've reverted to having the RG in front of my USG for now and do pass through and haven't had a single drop. I have the new router too and will be setting it up this weekend. 

I am not saying it's the eap_proxy's fault or the reason. I think something was going on that would make it drop and I believe it happened since the very beginning. Is there anyway I could further test it or I assume there's some debug I can turn on so when I try it with the new switch I can see?

**Comment by jaysoffian** [comment]
Please run with `--debug` in addition to the default options:

https://github.com/jaysoffian/eap_proxy/blob/master/eap_proxy.sh.example#L9

Then attach the log messages.
