### ISSUE TITLE
Firewalla support?

### ISSUE THREAD

**Issue by iogitio** [jaysoffian/eap_proxy#49]
A good contingent of people are jumping ship to Firewalla from USG. is it easily possible to adapt this to the firewalla gold?

**Comment by jaysoffian** [comment]
Sorry, but I don't know the first thing about Firewalla. I personally don't even run this on a USG... I'm still using it on my EdgeRouter 4 running EdgeOS 1.x. 

I'm always willing to consider a PR, but I'm somewhat hesitant to accept code that I have no ability to test. But, this project is BSD-licensed so anyone is welcome to fork it and add what they need.
