### ISSUE TITLE
Byte encoding of default gateway IP not correct.

### ISSUE THREAD

**Issue by keatontaylor** [jaysoffian/eap_proxy#8]
Gateway IP resolution on lines 172-172 of eap_proxy.py do not properly encode the default gateway IP. The IP is instead in reverse. Tested on ER-X running 1.10.7

**Comment by jaysoffian** [comment]
The reason for this is that the ER-X is a little endian device, while the MIPS based devices are big-endian. I'll have to make the script detect the model it's on or make this configurable.

**Comment by jaysoffian** [comment]
Fixed by 04a6578556.
